# Exercises

Using this chapter's housing dataset:

1. Try a support vector machine regressor (`sklearn.svm.SVR`), with various hyperparameters such as `kernel = "linear"` (with various values for the `C` hyperparameter) or `kernel = "rbf"` (with various values for the `C` & `gamma` hyperparameters). Don't worry about that these hyperparameters mean for now. How does the best `SVR` predictor perform?
2. Try replacing `GridSearchCV` with `RandomisedSearchCV`.
3. Try adding a transformer in the preparation pipeline to select only the most important attributes.
4. Try creating a single pipeline that does the full data preparation plus the final prediction.
5. Automatically explore some preparation options using `GridSearchCV`.

---

# 1.

In [1]:
import pandas as pd

housing = pd.read_csv("housing.csv")
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [2]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [3]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(housing, test_size = 0.2, random_state = 31)
X_train = train_set.drop("median_house_value", axis = 1)
y_train = train_set["median_house_value"]
X_test = test_set.drop("median_house_value", axis = 1)
y_test = test_set["median_house_value"]

With our data split, make sure splits are similar so it doesn't affect model evaluation.

In [4]:
train_set.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  16512.000000  16512.000000        16512.000000  16512.000000   
mean    -119.567325     35.628352           28.656734   2636.864220   
std        2.000261      2.135195           12.627148   2194.580225   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1446.000000   
50%     -118.500000     34.260000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.470000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    16347.000000  16512.000000  16512.000000   16512.000000   
mean       537.933933   1425.368702    499.572250       3.876215   
std        422.981140   1141.720172    383.384752       1.899114   
min          1.000000      6.000000      1.000000       0.499900   
25%        295.000000    788.000000    279.000000       2.566300   
50%        433.000000   1166.000000    408.000000       3.539400   
75%        648.000000   1730.000000    606.000000       4.760100   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        16512.000000  
mean        207153.583394  
std         115603.351513  
min          14999.000000  
25%         119550.000000  
50%         179800.000000  
75%         265300.000000  
max         500001.000000

In [5]:
test_set.describe()

longitude     latitude  housing_median_age   total_rooms  \
count  4128.000000  4128.000000         4128.000000   4128.000000   
mean   -119.579222    35.645899           28.570494   2631.358527   
std       2.016778     2.139180           12.419076   2129.221411   
min    -124.260000    32.560000            1.000000      6.000000   
25%    -121.800000    33.937500           18.000000   1451.000000   
50%    -118.480000    34.260000           29.000000   2125.000000   
75%    -118.020000    37.710000           37.000000   3133.750000   
max    -114.310000    41.810000           52.000000  27870.000000   

       total_bedrooms    population   households  median_income  \
count     4086.000000   4128.000000  4128.000000    4128.000000   
mean       537.616985   1425.908915   499.409399       3.848496   
std        414.989296   1094.782032   378.126352       1.902720   
min          2.000000      3.000000     2.000000       0.499900   
25%        297.000000    786.000000   281.000000       2.555100   
50%        443.000000   1164.500000   415.000000       3.519050   
75%        644.000000   1699.000000   600.000000       4.693500   
max       5419.000000  12153.000000  4930.000000      15.000100   

       median_house_value  
count         4128.000000  
mean        205664.750969  
std         114567.095074  
min          14999.000000  
25%         119900.000000  
50%         179500.000000  
75%         263300.000000  
max         500001.000000

Looks good enough, treat the numeric features & categorical features before training a model.

In [6]:
from sklearn.pipeline import Pipeline

# Numeric
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

rooms, bedrooms, population, households = [list(X_train.columns).index(col) 
                                           for col in ("total_rooms", "total_bedrooms", "population", "households")]

class CombinedAttributes(BaseEstimator, TransformerMixin):
    def __init__(self):
        self
    def fit(self, X, y = None):
        return self
    def transform(self, X, y = None):
        rooms_per_household = X[:, rooms]/X[:, households]
        population_per_household = X[:, population]/X[:, households]
        bedrooms_per_household = X[:, bedrooms]/X[:, households]
        return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_household]
        
num_pipeline = Pipeline([("imputer", SimpleImputer(strategy = "median")),
                         ("attribs_add", CombinedAttributes()),
                         ("std_scaler", StandardScaler())])
X_train_num = X_train.drop("ocean_proximity", axis = 1)
X_train_num_prepared = num_pipeline.fit_transform(X_train_num)

In [7]:
# Categorical
from sklearn.preprocessing import OneHotEncoder

cat_pipeline = Pipeline([("encoder", OneHotEncoder())])
X_train_cat = X_train[["ocean_proximity"]]
X_train_cat_prepared = cat_pipeline.fit_transform(X_train_cat)

In [8]:
# Combine numerical & categorical pipelines
from sklearn.compose import ColumnTransformer

num_attributes = list(X_train_num)
cat_attributes = list(X_train_cat)

full_pipeline = ColumnTransformer([("numeric", num_pipeline, num_attributes),
                                   ("categorical", cat_pipeline, cat_attributes)])
X_train_prepared = full_pipeline.fit_transform(X_train)

With the prepared data, we can now try a support vector machine regressor. Also, find best hyperparameters for svm regressor.

In [9]:
# Search for best combination of hyperparamters.
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

supportVectorRegressor = SVR()
param_search_space = [{"kernel":["linear"], "C":[130, 140, 150, 160, 170]},
                      {"kernel":["rbf"], "C":[130, 140, 150, 160, 170], "gamma":["scale", "auto"]}]
grid_search = GridSearchCV(supportVectorRegressor, param_search_space,
                           cv = 3, scoring = "neg_mean_squared_error",
                           return_train_score = True)
grid_search.fit(X_train_prepared, y_train)
grid_search.best_params_

{'C': 150, 'kernel': 'linear'}

We'll evaluate our svm model with its best performing hyperparameters.

In [16]:
from sklearn.model_selection import cross_val_score

svmRegressor = SVR(kernel = "linear", C = 150) # Add the best hyperparameters.
scores = cross_val_score(svmRegressor, X_train_prepared, y_train,
                         scoring = "neg_mean_squared_error", cv = 10)
print("Scores: ", np.sqrt(-scores))
print("Mean: ", np.sqrt(-scores).mean())
print("Standard Deviation: ", np.sqrt(-scores).std())

Scores:  [70543.66474464 71250.31665234 72756.5047003  69684.87362869
 70931.46957475 74669.02479433 69883.45732019 68639.8024736
 73108.93704201 71323.50227389]
Mean:  71279.15532047502
Standard Deviation:  1707.114464391755


Our svm regressor performs worse than our linear regression model, decision tree model, & random forests model. It does have more precise predictions, although it may be the result of having the same hyperparameters across different folds during cross-validation.

# 2.

Try randomised search instead of grid search.

In [15]:
from sklearn.model_selection import RandomizedSearchCV

supportVectorRegressor = SVR()
param_search_space = [{"kernel":["linear"], "C":[130, 140, 150, 160, 170]},
                      {"kernel":["rbf"], "C":[130, 140, 150, 160, 170], 
                       "gamma":[0.1, 0.3, 0.5, 1.0, 1.3, ]}]
random_search = RandomizedSearchCV(supportVectorRegressor, param_search_space,
                                   n_iter = 10, cv = 3, scoring = "neg_mean_squared_error",
                                   return_train_score = True)
random_search.fit(X_train_prepared, y_train)
random_search_params = random_search.best_params_
random_search_params

{'kernel': 'linear', 'C': 170}

In [18]:
svmRegressor = SVR(kernel = random_search_params["kernel"], 
                   C = random_search_params["C"]) # Add hyperparameters from randomised search.
scores = cross_val_score(svmRegressor, X_train_prepared, y_train,
                         scoring = "neg_mean_squared_error", cv = 10)
print("Scores: ", np.sqrt(-scores))
print("Mean: ", np.sqrt(-scores).mean())
print("Standard Deviation: ", np.sqrt(-scores).std())

Scores:  [70428.18263927 71266.7437871  72680.25483043 69529.14813222
 70786.55604906 74519.23126193 69712.34843959 68527.12675499
 72965.45415438 71179.52140621]
Mean:  71159.45674551773
Standard Deviation:  1709.6624786044213


# 3.

Try feature selection & put it in a pipeline. SVR models do not support feature importances, so I'll do this on a random forests model.

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

randomForests = RandomForestRegressor()
param_search_space = [{"n_estimators": [3, 10, 30], "max_features":[2, 4, 6, 8]},
                      {"bootstrap":[False], "n_estimators":[3, 10], "max_features": [2, 3, 4]}]
grid_search = GridSearchCV(randomForests, param_search_space, cv = 3,
                           scoring = "neg_mean_squared_error", return_train_score = True)
grid_search.fit(X_train_prepared, y_train)
grid_search.best_params_

{'max_features': 8, 'n_estimators': 30}

In [10]:
extra_attribs = ["rooms_per_hhold", "pop_per_hhold", "bedrooms_per_room"]
cat_encoder = OneHotEncoder()
cat_encoder.fit_transform(X_train_cat)
cat_encoded_attribs = list(cat_encoder.categories_[0])
attributes = num_attributes + extra_attribs + cat_encoded_attribs
attributes

feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

array([7.83187619e-02, 6.63108328e-02, 4.08715345e-02, 1.58853250e-02,
       1.42811703e-02, 1.52454076e-02, 1.38383175e-02, 3.89137344e-01,
       6.24083058e-02, 1.05741616e-01, 2.43272799e-02, 5.49648507e-03,
       1.60005713e-01, 3.14807876e-04, 3.33124233e-03, 4.48585600e-03])

Suppose we want the top *n* features. **Note to self:** cannot index by name.

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin

class TopNFeatures(BaseEstimator, TransformerMixin):
    def __init__(self, scores, n):
        self.scores = scores
        self.n = n
    def fit(self, X, y = None):
        self.top_n_features = np.sort(np.argpartition(self.scores, -n)[-n:])
        return self
    def transform(self, X):
        return X[:, list(self.top_n_features)]

In [12]:
n = 6
new_pipeline = Pipeline([("preparation", full_pipeline),
                         ("feature selection", TopNFeatures(feature_importances, n))])
new_pipeline.fit_transform(X_train)

array([[ 0.77858458, -0.79543244,  0.28202705, -0.32295769, -0.04687597,
         0.        ],
       [-1.26121131,  0.95153334, -0.21274505, -0.19073272, -0.02378648,
         0.        ],
       [ 0.10865162,  0.32393705, -0.02775842, -0.03381263, -0.06393588,
         1.        ],
       ...,
       [-1.26121131,  0.93748267,  0.78364466,  0.34130536,  0.07609582,
         0.        ],
       [ 0.58360409, -0.67366003, -0.14507985, -0.39117374, -0.06557157,
         0.        ],
       [ 1.29353305, -1.36214252,  0.33557997,  0.44339882, -0.01003082,
         0.        ]])

In [13]:
X_train_prepared[:, np.sort(np.argpartition(feature_importances, -n)[-n:])]

array([[ 0.77858458, -0.79543244,  0.28202705, -0.32295769, -0.04687597,
         0.        ],
       [-1.26121131,  0.95153334, -0.21274505, -0.19073272, -0.02378648,
         0.        ],
       [ 0.10865162,  0.32393705, -0.02775842, -0.03381263, -0.06393588,
         1.        ],
       ...,
       [-1.26121131,  0.93748267,  0.78364466,  0.34130536,  0.07609582,
         0.        ],
       [ 0.58360409, -0.67366003, -0.14507985, -0.39117374, -0.06557157,
         0.        ],
       [ 1.29353305, -1.36214252,  0.33557997,  0.44339882, -0.01003082,
         0.        ]])

# 4. 
Create a pipeline to do it all: prepare data, select best features, predict on new data.

In [15]:
does_it_all_pipeline = Pipeline([("preparation", full_pipeline),
                                 ("feature_selection", TopNFeatures(feature_importances, n)),
                                 ("random_forests", RandomForestRegressor(**grid_search.best_params_))]) # rerun 3. before running this one
does_it_all_pipeline.fit(X_train, y_train)                                 

Pipeline(steps=[('preparation',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('attribs_add',
                                                                   CombinedAttributes()),
                                                                  ('std_scaler',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income']),
                                                 ('categorical',
                                                  Pipeline(...
                ('feature_selection',
                 TopNFeatures(n=6,
                              scores=array([7.83187619e-02, 6.63108328e-02, 4.08715345e-02, 1.58853250e-02,
       1.42811703e-02, 1.52454076e-02, 1.38383175e-02, 3.89137344e-01,
       6.24083058e-02, 1.05741616e-01, 2.43272799e-02, 5.49648507e-03,
       1.60005713e-01, 3.14807876e-04, 3.33124233e-03, 4.48585600e-03]))),
                ('random_forests',
                 RandomForestRegressor(max_features=8, n_estimators=30))])

In [31]:
predictions = does_it_all_pipeline.predict(X_test.iloc[:5, :])
predictions

array([153410.        , 150726.66666667, 251110.        ,  86416.66666667,
       131836.66666667])

In [29]:
y_test[:5]

15430    147500.0
10950    158000.0
14574    303100.0
9603      60900.0
6005     113600.0
Name: median_house_value, dtype: float64

In [33]:
from sklearn.metrics import mean_squared_error

final_mse = mean_squared_error(y_test[:5], predictions)
final_rmse = np.sqrt(final_mse)
final_rmse

27475.319349069145

# 5.
Not sure what this question means.

In [34]:
?GridSearchCV

Init signature:
GridSearchCV(
    estimator,
    param_grid,
    *,
    scoring=None,
    n_jobs=None,
    refit=True,
    cv=None,
    verbose=0,
    pre_dispatch='2*n_jobs',
    error_score=nan,
    return_train_score=False,
)
Docstring:     
Exhaustive search over specified parameter values for an estimator.

Important members are fit, predict.

GridSearchCV implements a "fit" and a "score" method.
It also implements "score_samples", "predict", "predict_proba",
"decision_function", "transform" and "inverse_transform" if they are
implemented in the estimator used.

The parameters of the estimator used to apply these methods are optimized
by cross-validated grid-search over a parameter grid.

Read more in the :ref:`User Guide <grid_search>`.

Parameters
----------
estimator : estimator object
    This is assumed to implement the scikit-learn estimator interface.
    Either estimator needs to provide a ``score`` function,
    or ``scoring`` must be passed.

param_grid : dict or list of